#!/usr/bin/env bash

# read active branch
current_branch="$(git rev-parse --abbrev-ref HEAD)"

# check for jira.prefix value in git config
jira_prefix=$(git config jira.prefix)
if [ -z "$jira_prefix" ];then
    echo "Cannot commit: missing jira prefix value"
    echo "Please add to git config. For example, if your jira project uses this notation: SHS-123, then execute"
    echo ""
    echo "git config jira.prefix SHS"
    echo ""
    exit 1
fi

# regex to validate in commit msg
commit_regex="($jira_prefix-[0-9]+.+)"
error_msg="Aborting commit. Your commit message is missing a reference to Jira ticket, e.g. ('$jira_prefix-123 message')"

[[ $1 =~ $commit_regex ]] && exit 0
echo "$error_msg" >&2
exit 1
